CREATE TABLE USERS (
    USERNAME VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    DATE_OF_PERMIT DATE NOT NULL,
    DATE_OF_BIRTH DATE NOT NULL,
    PRIMARY KEY (EMAIL)
);

CREATE TABLE TEST_CENTERS (
    ID INTEGER NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    CITY VARCHAR(255) NOT NULL,
    COUNTRY VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE ROUTES (
    ID INT NOT NULL AUTO_INCREMENT,
    TEST_CENTER_ID INT NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (TEST_CENTER_ID) REFERENCES TEST_CENTERS(ID) ON DELETE CASCADE
);

CREATE TABLE WAYPOINTS (
    ID INT NOT NULL AUTO_INCREMENT,
    ROUTE_ID INT NOT NULL,
    LATITUDE DECIMAL(10, 8) NOT NULL,
    LONGITUDE DECIMAL(11, 8) NOT NULL,
    NEXT_LATITUDE DECIMAL (11, 8) NOT NULL,
    NEXT_LONGITUDE DECIMAL (11, 8) NOT NULL,
    INSTRUCTION VARCHAR(255),
    DISTANCE VARCHAR(255),
    DURATION VARCHAR (255),
    PRIMARY KEY (ID),
    FOREIGN KEY (ROUTE_ID) REFERENCES ROUTES(ID) ON DELETE CASCADE,
    INDEX (ROUTE_ID)
);

CREATE TABLE TURNS (
    ID INT NOT NULL AUTO_INCREMENT,
    ROUTE_ID INT NOT NULL,
    LATITUDE DECIMAL(10, 8) NOT NULL,
    LONGITUDE DECIMAL(11, 8) NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (ROUTE_ID) REFERENCES ROUTES(ID) ON DELETE CASCADE,
    INDEX (ROUTE_ID)
);