CREATE TABLE
    USERS (
        USERNAME VARCHAR(255) NOT NULL,
        PASSWORD VARCHAR(255) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        EMAIL VARCHAR(255) NOT NULL,
        DATE_OF_PERMIT DATE,
        DATE_OF_BIRTH DATE NOT NULL,
        ROLE VARCHAR(255) NOT NULL,
        PRIMARY KEY (EMAIL)
    );

CREATE TABLE
    TEST_CENTERS (
        ID INTEGER NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        CITY VARCHAR(255) NOT NULL,
        COUNTRY VARCHAR(255) NOT NULL,
        PRIMARY KEY (ID)
    );

CREATE TABLE
    ROUTES (
        ID INT NOT NULL AUTO_INCREMENT,
        TEST_CENTER_ID INT NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        PRIMARY KEY (ID),
        FOREIGN KEY (TEST_CENTER_ID) REFERENCES TEST_CENTERS (ID) ON DELETE CASCADE
    );

CREATE TABLE
    WAYPOINTS (
        ID INT NOT NULL AUTO_INCREMENT,
        ROUTE_ID INT NOT NULL,
        LATITUDE DECIMAL(10, 8) NOT NULL,
        LONGITUDE DECIMAL(11, 8) NOT NULL,
        NEXT_LATITUDE DECIMAL(11, 8) NOT NULL,
        NEXT_LONGITUDE DECIMAL(11, 8) NOT NULL,
        INSTRUCTION VARCHAR(255),
        DISTANCE VARCHAR(255),
        DURATION VARCHAR(255),
        PRIMARY KEY (ID),
        FOREIGN KEY (ROUTE_ID) REFERENCES ROUTES (ID) ON DELETE CASCADE,
        INDEX (ROUTE_ID)
    );

CREATE TABLE
    TURNS (
        ID INT NOT NULL AUTO_INCREMENT,
        ROUTE_ID INT NOT NULL,
        LATITUDE DECIMAL(10, 8) NOT NULL,
        LONGITUDE DECIMAL(11, 8) NOT NULL,
        PRIMARY KEY (ID),
        FOREIGN KEY (ROUTE_ID) REFERENCES ROUTES (ID) ON DELETE CASCADE,
        INDEX (ROUTE_ID)
    );

CREATE TABLE
    MANEUVER (
        ID INT NOT NULL AUTO_INCREMENT,
        ROUTE_ID INT NOT NULL,
        LATITUDE DECIMAL(10, 8) NOT NULL,
        LONGITUDE DECIMAL(11, 8) NOT NULL,
        TYPE VARCHAR(255) NOT NULL,
        CORD_TYPE VARCHAR(255) NOT NULL,
        PRIMARY KEY (ID),
        FOREIGN KEY (ROUTE_ID) REFERENCES ROUTES (ID) ON DELETE CASCADE,
        INDEX (ROUTE_ID)
    );

CREATE TABLE
    FEEDBACK (
        ID INT NOT NULL AUTO_INCREMENT,
        ROUTE_ID INT NOT NULL,
        MANUEVER_TYPE VARCHAR(255) NOT NULL,
        SCORE INT NOT NULL,
        USER_EMAIL VARCHAR(255) NOT NULL,
        FOREIGN KEY (ROUTE_ID) REFERENCES ROUTES (ID) ON DELETE CASCADE,
        FOREIGN KEY (USER_EMAIL) REFERENCES USERS (EMAIL) ON DELETE CASCADE,
        PRIMARY KEY (ID)
    );

CREATE TABLE
    QUIZZES (
        ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
        TITLE VARCHAR(255),
        DESCRIPTION VARCHAR(255)
    );

CREATE TABLE
    QUESTIONS (
        ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
        quiz_id INTEGER NOT NULL,
        question_text TEXT NOT NULL,
        image_path VARCHAR(255),
        FOREIGN KEY (quiz_id) REFERENCES QUIZZES (ID)
    );

CREATE TABLE
    OPTIONS (
        ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
        quiz_id INTEGER NOT NULL,
        question_id INTEGER NOT NULL,
        option_text TEXT NOT NULL,
        is_correct BOOLEAN NOT NULL,
        FOREIGN KEY (question_id) REFERENCES QUESTIONS (ID),
        FOREIGN KEY (quiz_id) REFERENCES QUIZZES (ID)
    );

CREATE TABLE
    INSTRUCTOR_LEARNER (
        ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
        LEARNER_EMAIL VARCHAR(255) NOT NULL,
        INSTRUCTOR_EMAIL VARCHAR(255) NOT NULL,
        FOREIGN KEY (LEARNER_EMAIL) REFERENCES USERS (EMAIL) ON DELETE CASCADE,
        FOREIGN KEY (INSTRUCTOR_EMAIL) REFERENCES USERS (EMAIL) ON DELETE CASCADE
    );

CREATE TABLE
    LESSONS (
        ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
        LESSON_NAME VARCHAR(255) NOT NULL
    );

CREATE TABLE
    LESSON_FEEDBACK (
        ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
        LESSON_ID INT NOT NULL,
        LEARNER_EMAIL VARCHAR(255) NOT NULL,
        INSTRUCTOR_EMAIL VARCHAR(255) NOT NULL,
        FEEDBACK VARCHAR(255),
        STATUS VARCHAR(255),
        CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (LESSON_ID) REFERENCES LESSONS (ID) ON DELETE CASCADE,
        FOREIGN KEY (LEARNER_EMAIL) REFERENCES USERS (EMAIL) ON DELETE CASCADE,
        FOREIGN KEY (INSTRUCTOR_EMAIL) REFERENCES USERS (EMAIL) ON DELETE CASCADE
    );

CREATE TABLE
    CHECKLIST (
        ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
        CHECKLIST_NAME VARCHAR(255) NOT NULL,
        CHECKLIST_STATUS BOOLEAN NOT NULL,
        USER_EMAIL VARCHAR(255) NOT NULL,
        FOREIGN KEY (USER_EMAIL) REFERENCES USERS (EMAIL) ON DELETE CASCADE
    );

CREATE TABLE
    SESSIONS (
        ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
        LEARNER_EMAIL VARCHAR(255) NOT NULL,
        INSTRUCTOR_EMAIL VARCHAR(255) NOT NULL,
        SESSION_DATE DATE NOT NULL,
        SESSION_START_TIME TIMESTAMP NOT NULL,
        SESSION_END_TIME TIMESTAMP NOT NULL,
        STATUS VARCHAR(255),
        FOREIGN KEY (LEARNER_EMAIL) REFERENCES USERS (EMAIL) ON DELETE CASCADE,
        FOREIGN KEY (INSTRUCTOR_EMAIL) REFERENCES USERS (EMAIL) ON DELETE CASCADE
    );
ALTER TABLE SESSIONS
ADD COLUMN BOOKED_BY VARCHAR(255),
ADD FOREIGN KEY (BOOKED_BY) REFERENCES USERS (EMAIL) ON DELETE CASCADE;