CREATE TABLE USERS (
	USERNAME VARCHAR(255) NOT NULL,
	PASSWORD VARCHAR(255) NOT NULL,
	FIRST_NAME VARCHAR(255) NOT NULL,
	LAST_NAME VARCHAR(255),
	EMAIL VARCHAR(255) NOT NULL,
	DATE_OF_BIRTH DATE NOT NULL,
	PRIMARY KEY (EMAIL) 
);
