CREATE TABLE USERS (
	USERNAME VARCHAR(255) NOT NULL,
	PASSWORD VARCHAR(255) NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	EMAIL VARCHAR(255) NOT NULL,
	DATE_OF_PERMIT DATE NOT NULL,
	DATE_OF_BIRTH DATE NOT NULL,
	PRIMARY KEY (EMAIL) 
);